/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_powerline_status.h"
#include "bar_status.h"
#include "bar_winicon.h"
#include "bar_tabgroups.h"
#include "bar_taggrid.h"
#include "bar_wintitle.h"
#include "bar_flexwintitle.h"
#include "bar_wintitle_floating.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "exresize.h"
#include "killunsel.h"
#include "moveresize.h"
#include "pertag.h"
#include "placemouse.h"
#include "push.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "seamless_restart.h"
#include "setborderpx.h"
#include "shift.h"
#include "shiftviewclients.h"
#include "sticky.h"
#include "swallow.h"
#include "swapfocus.h"
#include "tapresize.h"
#include "vanitygaps.h"
#include "warp.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_centeredmaster.h"
#include "layout_deck.h"
#include "layout_monocle.h"
#include "layout_tile.h"

