/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_powerline_status.c"
#include "bar_status.c"
#include "bar_winicon.c"
#include "bar_tabgroups.c"
#include "bar_taggrid.c"
#include "bar_wintitle.c"
#include "bar_flexwintitle.c"
#include "bar_wintitle_floating.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "dragcfact.c"
#include "exresize.c"
#include "focusurgent.c"
#include "killunsel.c"
#include "moveresize.c"
#include "pertag.c"
#include "placemouse.c"
#include "push.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "setborderpx.c"
#include "shift.c"
#include "shiftviewclients.c"
#include "sticky.c"
#include "swallow.c"
#include "swapfocus.c"
#include "tapresize.c"
#include "vanitygaps.c"
#include "warp.c"
#include "xrdb.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_centeredmaster.c"
#include "layout_deck.c"
#include "layout_monocle.c"
#include "layout_tile.c"

